default_config:
logger:
  default: error
  logs:
    custom_components.power_tariff: debug

power_tariff:
  monitor_entity: "xxxx"
  tariffs:
    - name: dag
      limit_kwh: 1000
      over_limit_acceptance: 0.2
      over_limit_acceptance_seconds: 60

  devices:
    - entity: "something"
      enabled: true
